version: '3.7'
services:
  checker:
    image: t7tran/tls-expiry-checker:0.1.0
    read_only: true
    user: checker
    environment:
      # DEBUG: 'true'
      VERBOSE: 'true'
      WARNING_DAYS: 55
      EXIT_ON_ERROR: end # first, end or empty
      TARGET_DOMAIN_PORT_IPS: |
        one.one.one.one:443:1.1.1.1
        one.one.one.one:1.1.1.1
        one.one.one.one:443
        one.one.one.one
